name: Lint and Test

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: '1.17.12'
  RUST_TOOLCHAIN: '1.69.0'

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup toolchain install ${{ env.RUST_TOOLCHAIN }} --component clippy, rustfmt

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run fmt
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy -- --deny=warnings

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Linux dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev

      - name: Install Rust
        run: rustup toolchain install ${{ env.RUST_TOOLCHAIN }}

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cache Solana binaries
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/solana
            ~/.local/share/solana
          key: ${{ runner.os }}-${{ env.SOLANA_VERSION }}

      - name: Install Solana
        run: |
          echo Installing Solana v${{ env.SOLANA_VERSION }}...🧬
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          echo Generating keypair...
          solana-keygen new -o "$HOME/.config/solana/id.json" --no-passphrase --silent

      # - name: Install BPF tools
      #   # Note: as a workaround for cargo build-bpf issue run it and ignore errors to install the BPF tools
      #   # https://github.com/solana-labs/solana/issues/26583
      #   run: cargo build-bpf || true

      # - name: Build dependencies
      #   run: cargo +bpf build-bpf

      # - name: Run bpf tests
      #   run: cargo +bpf test-bpf
      - name: Build
        run: |
          cargo build-sbf || true
          cargo +solana build-sbf
